#!/bin/sh

# homebrew
echo "Checking homebrew packages..."
brew update > /dev/null 2>&1;
new_packages=$(brew outdated)
new_casks=$(brew outdated --cask)
num_casks=$(echo $new_casks | wc -w)
num_packages=$(echo $new_packages | wc -w)

if [ $num_packages -gt 0 -o $num_casks -gt 0 ]; then
    echo "New package updates available:"
    for package in $new_packages; do
	echo "   * $package";
    done
    for cask in $new_casks; do
	echo "   * $cask (cask)";
    done
else
    echo "No new package updates available."
fi

# macOS
echo "Checking macOS updates..."
softwareupdate -l | tail +5
